/**
 * The abduction countdown track — Luke, 2026-09-22: a ship image travels
 * along a pre-set curved track (drawn onto `cardboard-panel-track.png`)
 * toward the player's avatar; how far along it is is the countdown. "Its
 * centre of mass... always remains in the centre of the track line" — so
 * this isn't a couple of hand-picked keypoints like the abduction-confirm
 * ship's path (skyPath.js's ABDUCT_SHIP_KEYPOINTS), it's measured directly
 * off the actual track artwork's pixels: for each row of the drawn line,
 * the horizontal centre of its ink. Regenerate by rerunning that same
 * measurement against new artwork rather than hand-editing these numbers.
 *
 * Coordinates are percentages of the panel's own PANEL_SIZE (1024x546),
 * same space every other cardboard-UI element is positioned in.
 *
 * Generated by skeletonizing the track artwork's ink down to a 1px-wide
 * centreline (`skimage.morphology.skeletonize`) and walking it as a graph
 * from one true endpoint to the other (`networkx.shortest_path`) — not by
 * taking each row's horizontal centre, which was the first approach here
 * and was wrong. Luke, 2026-09-22, after that version cut across empty
 * space near the top: "I don't know what 'decorative loop' you are
 * talking about; there is only a continuous track... this must be some
 * misreading of the image." He was right — skeletonizing the actual
 * artwork confirms one single unbroken stroke, no loop. The real bug was
 * that a per-row centre only means "a point on the curve" where the curve
 * is roughly vertical; near the top here it runs nearly horizontal, so a
 * horizontal row-slice cuts across a long stretch of it at a shallow
 * angle and the row's centre lands in open space, not on the ink. Graph
 * skeletonization has no preferred direction, so it doesn't have this
 * failure mode — regenerate this array the same way for any future track
 * artwork rather than going back to row/column centres.
 */
export const TRACK_PATH = [
  { x: 94.63, y: 20.88 },
  { x: 93.95, y: 20.7 },
  { x: 93.26, y: 20.15 },
  { x: 92.58, y: 19.6 },
  { x: 91.89, y: 19.05 },
  { x: 91.21, y: 18.68 },
  { x: 90.53, y: 18.32 },
  { x: 89.84, y: 17.95 },
  { x: 89.16, y: 17.77 },
  { x: 88.48, y: 17.58 },
  { x: 87.79, y: 17.4 },
  { x: 87.11, y: 17.22 },
  { x: 86.43, y: 17.22 },
  { x: 85.74, y: 17.22 },
  { x: 85.06, y: 17.22 },
  { x: 84.38, y: 17.4 },
  { x: 83.69, y: 17.58 },
  { x: 83.01, y: 17.77 },
  { x: 82.32, y: 17.95 },
  { x: 81.64, y: 18.32 },
  { x: 80.96, y: 18.86 },
  { x: 80.27, y: 19.41 },
  { x: 79.59, y: 19.96 },
  { x: 78.91, y: 20.7 },
  { x: 78.22, y: 21.61 },
  { x: 77.64, y: 22.71 },
  { x: 77.05, y: 23.99 },
  { x: 76.66, y: 25.27 },
  { x: 76.46, y: 26.56 },
  { x: 76.37, y: 27.84 },
  { x: 76.27, y: 29.12 },
  { x: 76.37, y: 30.4 },
  { x: 76.46, y: 31.68 },
  { x: 76.66, y: 32.97 },
  { x: 77.05, y: 34.25 },
  { x: 77.54, y: 35.53 },
  { x: 78.22, y: 36.81 },
  { x: 78.91, y: 37.73 },
  { x: 79.59, y: 38.83 },
  { x: 80.27, y: 39.56 },
  { x: 80.96, y: 40.29 },
  { x: 81.64, y: 41.03 },
  { x: 82.32, y: 41.76 },
  { x: 83.01, y: 42.31 },
  { x: 83.69, y: 43.04 },
  { x: 84.38, y: 43.77 },
  { x: 85.06, y: 44.51 },
  { x: 85.74, y: 45.42 },
  { x: 86.43, y: 46.34 },
  { x: 87.11, y: 47.62 },
  { x: 87.7, y: 48.9 },
  { x: 88.18, y: 50.18 },
  { x: 88.48, y: 51.47 },
  { x: 88.57, y: 52.75 },
  { x: 88.67, y: 54.03 },
  { x: 88.67, y: 55.31 },
  { x: 88.48, y: 56.59 },
  { x: 88.28, y: 57.88 },
  { x: 87.89, y: 59.16 },
  { x: 87.5, y: 59.89 },
];

// The blue placeholder card's own bounds in Luke's reference mockup,
// measured the same way — "for the prototype, choose any character card
// and put it in place" (the actual character art is swapped in later).
export const AVATAR_CARD = { left: 79.1, top: 60.81, width: 12.01, height: 34.98 };

/** Position along TRACK_PATH at `progress` (0 = start, 1 = at the avatar), in panel-percentage space. Index-interpolated, not true arc-length — the points are close enough together (every 5 source px) that this reads as constant speed. */
export function pointOnTrack(progress) {
  const t = Math.max(0, Math.min(1, progress)) * (TRACK_PATH.length - 1);
  const i = Math.floor(t);
  const frac = t - i;
  const a = TRACK_PATH[i];
  const b = TRACK_PATH[Math.min(i + 1, TRACK_PATH.length - 1)];
  return { x: a.x + (b.x - a.x) * frac, y: a.y + (b.y - a.y) * frac };
}
